Added partial support for Element.scrollIntoView()
ampproject/worker-dom pull request #1033
Opened 2021-03-22 20:27 UTC by andrei0x309

Since there isn't a way now to programmatically scroll to an element, I thought it would be nice if there was some basic support for that.

I've seen some issues like [issue-1009](https://github.com/ampproject/worker-dom/issues/1009)  that can be resolved if `worker-dom` supports `scrollIntoView()`, I only added basic support(no support for method params) since it required less code, also the 'smooth' option today is supported by using CSS in most browsers, and those that don't support CSS smooth, they don't support `scrollIntoView()` with smooth as an option.

I couldn't write a test since I believe `Window.pageY` was necessary and is not supported by `worker-dom`, but I wrote a demo instead of a test. 

Thanks, and I appreciate any feedback.

2021-03-22 20:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/worker-dom?pullRequest=1033) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/worker-dom?pullRequest=1033) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/worker-dom?pullRequest=1033) it.</sub>

2021-03-24 16:04 UTC, samouri commented
@andrei0x309, thank you so much for the PR! At initial glance this looks great. I'll give it a more thorough review later today.

One quick note: we usually write unit tests that ensure messages passed between main-thread and worker-thread are as expected, as opposed to making them integration tests (which could involve checking `Window.pageY`).

Therefore potential tests you could write:
1. Ensure worker-thread sends the expected message to the main-thread when Element.scrollIntoView is called.
2. Ensure main-thread calls the expected DOM API when receiving the correct message from the worker-thread


Here's an example of a test expecting mutation events to be sent from the worker-thread:
https://github.com/ampproject/worker-dom/blob/f5da1e6231d552618290ae07cdfd4ac547b3ff12/src/test/mutation-transfer/amp.test.ts#L42-L57

2021-03-24 17:14 UTC, andrei0x309 commented
@samouri Thanks, for the reply, 

I added the transfer mutation test for scrollIntoView().

2021-03-24 18:43 UTC, samouri requested changes
Excellent PR :). Only one blocking request (to ensure it is considered user visible).
Otherwise LGTM.

As an action item on my side I'm going to make a new command, `yarn format` for automatically running prettier on files

2021-03-24 18:43 UTC, samouri commented on src/transfer/TransferrableMutation.ts
> +    case TransferrableMutationType.SCROLL_INTO_VIEW:
I know the comment describes user-visible changes to _DOM_, but I actually think the intention is any user-visible change (which would include this). Can you delete this line s.t. it returns true
```suggestion
```

2021-03-24 18:43 UTC, samouri commented on src/test/mutation-transfer/scrollIntoView.test.ts
> +import { TransferrableKeys } from '../../transfer/TransferrableKeys';
nit: did all of the prepush checks run? we normally run `prettier` over the codebase, and the whitespace here doesn't look right.

2021-03-24 18:43 UTC, samouri commented on demo/scroll-into-view/scroll-into-view.js
> +  });
nit: whitespace here doesn't look right. 
```suggestion
});
```

2021-03-24 18:43 UTC, samouri commented on demo/scroll-into-view/scroll-into-view.js
> +  });
```suggestion
});  
```

2021-03-24 18:43 UTC, samouri commented on demo/scroll-into-view/index.html
> +      <p>Demo of <b>element.scrrollIntoView()</b></p>
```suggestion
      <p>Demo of <b>element.scrollIntoView()</b></p>
```

2021-03-24 18:55 UTC, andrei0x309 commented on src/transfer/TransferrableMutation.ts
> +    case TransferrableMutationType.SCROLL_INTO_VIEW:
Yeah, you're completely right I only thought of DOM and not considered the scroll changing position as a user-visible change which it actually is.

2021-03-24 18:57 UTC, andrei0x309 commented on src/test/mutation-transfer/scrollIntoView.test.ts
> +import { TransferrableKeys } from '../../transfer/TransferrableKeys';
This time I didn't. 
Sorry for that.

2021-03-24 19:37 UTC, samouri approved these changes

2021-03-24 19:38 UTC, merged