Storage: fix clear and removeItem
ampproject/worker-dom pull request #1136
Opened 2022-02-22 17:02 UTC by samouri

The mutations array usually contains an index into StringContext for
value of key/value in the operation. Historically, "delete" was
modeled as 0th index into the array. Unfortunately, this didn't make
sense if the first SET op was genuinely referring to the 0th string
value (See #1035).

While this fixed the first get/set operation, it also meant that deletes
were no longer possible! This PR now models the delete operation as a -1
in the unsigned mutation array, corresponding to 2^16-1.

2022-02-22 20:30 UTC, jridgewell commented on src/transfer/Messages.ts
> +// Deletion is specified as a -1, which when placed into the array becomes 2^16-1.
Why are we setting them to `-1` in the first place? Wouldn't `0` work?

2022-02-22 20:49 UTC, samouri commented on src/transfer/Messages.ts
> +// Deletion is specified as a -1, which when placed into the array becomes 2^16-1.
0 is overloaded. It can also mean the 0th index into the Strings array

2022-02-22 23:38 UTC, jridgewell commented on src/transfer/Messages.ts
> +// Deletion is specified as a -1, which when placed into the array becomes 2^16-1.
Just define it as index as the `+ 1` of the strings index? Then 0 is impossible.

2022-02-23 20:07 UTC, samouri commented
*update / background**
The main-thread code holds on to an array of strings, called `StringContext`. This way the worker-thread only has to send any string over the postMessage interface once. It can then refer to that string via its index into the array. When a value might sometimes exist and might be null, the worker-thread historically had passed in the `0th` index. Unfortunately, that index wasn't actually reserved, so it could also have a string in it & be necessary during hydration.

This PR reserves the 0th slot in main-thread StringContext, and starts the count of the worker-thread from 1.

2022-02-23 20:15 UTC, samouri commented on src/transfer/Messages.ts
> +// Deletion is specified as a -1, which when placed into the array becomes 2^16-1.
Always sending over +1 from the worker seems messier on both ends than reserving the 0th index. WDYT

2022-02-24 18:53 UTC, samouri commented
After a discussion with @jridgewell, we agreed that while reserving 0th slot would be simpler, it may have  unexpected ramifications to the codebase vs isolating to a single processor. Using the +1 in worker, -1 in main-thread approach to isolate the change.

Can do the 0 reservation in a future PR

2022-02-24 19:24 UTC, jridgewell requested changes

2022-02-24 19:24 UTC, jridgewell commented on src/worker-thread/Storage.ts
> +        store(key) + 1,
There's a `store(key)` and `store(stringValue)` on Line 54 above that need a `+ 1`.

2022-02-24 19:29 UTC, samouri commented on src/worker-thread/Storage.ts
> +        store(key) + 1,
You're right (of course)! Both the get and set flow use the same logic for determining key/value. I need to figure out why no test cases broke.

2022-02-28 15:10 UTC, samouri commented on src/worker-thread/Storage.ts
> +        store(key) + 1,
Ah. Because there are no integration tests. Just updated the unit tests -- but this is an obvious gap in worker-dom tests.

2022-02-28 18:33 UTC, jridgewell approved these changes

2022-02-28 19:19 UTC, merged