Unsubscription/removing "on" listener must not cause an error
ampproject/worker-dom pull request #1148
Opened 2023-06-30 21:19 UTC by ddenisyuk

Removing of event listener with in a way like: `element.onclick = null;`, stores `null` as a handler.

2023-06-30 21:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/worker-dom?pullRequest=1148) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/worker-dom?pullRequest=1148) before we can accept your contribution.<br/><hr/>**Denys Denysiuk** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/worker-dom?pullRequest=1148) it.</sub>

2023-07-05 19:17 UTC, olitvinenko approved these changes

2023-08-09 20:41 UTC, powerivq requested changes
Thanks for the contribution. LGTM otherwise.

2023-08-09 20:41 UTC, powerivq commented on src/worker-thread/dom/HTMLElement.ts
> +        if (typeof value === 'function') {
Can we do `value instanceof Function`?

2023-08-22 11:59 UTC, ddenisyuk commented on src/worker-thread/dom/HTMLElement.ts
> +        if (typeof value === 'function') {
sure, no problem

2023-08-22 16:53 UTC, powerivq approved these changes

2023-08-22 16:54 UTC, merged