Refactor output
ampproject/worker-dom pull request #929
Opened 2020-09-03 18:32 UTC by kristoferbaxter

Move to `amp-debug` and `amp-production` outputs.

2020-09-03 23:58 UTC, samouri requested changes
LGTM. 
We also need to update some of the filesize checks (and add the ones that don't exist yet. This is something I had missed when adding `nodom`)

2020-09-03 23:58 UTC, samouri commented on config/rollup.main-thread.js
> +  {
note: we don't currently have the setup to be able to switch to main-thread debug variant ([1](https://github.com/ampproject/amphtml/blob/master/extensions/amp-script/0.1/amp-script.js#L17)), but this would be nice to add.

2020-09-03 23:58 UTC, samouri commented on config/rollup.worker-thread.js
> -      banner: 'var WORKER_DOM_DEBUG = /log|development/i.test(location.hash);',
happy to see this go away :). We'll need to pick the correct one based on dev/prod builds.

2020-09-04 00:41 UTC, kristoferbaxter commented
Added tracking for the `nodom` variant.

2020-09-04 15:03 UTC, samouri approved these changes

2020-09-08 16:11 UTC, merged