decode numeric html entitites
ampproject/worker-dom pull request #947
Opened 2020-09-17 21:26 UTC by samouri

Addressed the easy half of https://github.com/ampproject/worker-dom/issues/613

cc @caroqliu

2020-09-17 22:40 UTC, jridgewell requested changes

2020-09-17 22:40 UTC, jridgewell commented on src/third_party/html-parser/html-parser.ts
> +  return html.replace(/&#(x?\d+);?/g, function (s, entity) {
We need to parse hex entities and number entities.
```suggestion
  return html.replace(/&#(?:x([a-f\d]+)|(\d+));?/ig, function (s, hex, num) {
```

2020-09-17 22:40 UTC, jridgewell commented on src/third_party/html-parser/html-parser.ts
> +    if (!(isNaN(code) || code < -32768 || code > 65535)) {
What's up with -32768? But entities can definitely go above 65535, eg `&#x1F4A9;`

2020-09-17 23:32 UTC, samouri commented on src/third_party/html-parser/html-parser.ts
> +  return html.replace(/&#(x?\d+);?/g, function (s, entity) {
ah right, hex means letters too

2020-09-17 23:36 UTC, samouri commented on src/third_party/html-parser/html-parser.ts
> +    if (!(isNaN(code) || code < -32768 || code > 65535)) {
Good choice of example :P. So that entity is actually parsed as multiple codepoints. See the mdn description: 
```
A sequence of numbers that are UTF-16 code units. The range is between 0 and 65535 (0xFFFF). Numbers greater than 0xFFFF are truncated. No validity checks are performed.
```

`&#x1F4A9;` --> `String.fromCharCode([55357, 56489])`

2020-09-18 00:11 UTC, jridgewell commented on src/third_party/html-parser/html-parser.ts
> +      chr = String.fromCharCode(code);
We still need to match 💩. When greater than 65535, you can calculate the code points as:

```js
function encode(code) {
  code -= 0x10000;
  return [0xd800 | ((code >> 10) & 0x3ff), 0xdc00 | (code & 0x3ff)];
}
String.fromCharCode(...encode(0x1F4A9))
```

2020-09-18 00:11 UTC, jridgewell commented on src/third_party/html-parser/html-parser.ts
> +    if (!(isNaN(code) || code < 0 || code > 65535)) {
From our regex, it's impossible to get a negative number.

2020-09-18 00:11 UTC, jridgewell commented on src/third_party/html-parser/html-parser.ts
> +  return html.replace(/&#(x?[\da-zA-Z]+);?/g, function (s, entity) {
Hex is `a-f`, not `a-z`.

2020-09-18 03:34 UTC, samouri commented on src/third_party/html-parser/html-parser.ts
> +      chr = String.fromCharCode(code);
can you...explain how this works?

2020-09-18 03:43 UTC, samouri commented on src/third_party/html-parser/html-parser.ts
> +      chr = String.fromCharCode(code);
Ah, ok. Just read about surrogate pairs, so there can only ever be 2. Any objection to using `fromCodePoint` instead?

2020-09-18 04:33 UTC, patrickkettner commented on src/third_party/html-parser/html-parser.ts
> +      chr = String.fromCharCode(code);
I don't believe we were ever able to ship `fromCodePoint` in IE11, if you are needing to support that

2020-09-18 05:23 UTC, samouri commented on src/third_party/html-parser/html-parser.ts
> +      chr = String.fromCharCode(code);
IE11 support is already broken until we [start polyfilling](https://github.com/ampproject/worker-dom/pull/886/files). Once we are, `fromCodePoint` has a [polyfill available](https://github.com/zloirock/core-js/blob/v3.6.5/packages/core-js/modules/es.string.from-code-point.js) in core-js.

2020-09-18 05:49 UTC, jridgewell approved these changes

2020-09-18 05:49 UTC, jridgewell commented on src/third_party/html-parser/html-parser.ts
> +  return html.replace(/&#(x?[\da-fA-F]+);?/g, function (s, entity) {
The `x` can be `X`, too.

```suggestion
  return html.replace(/&#(x?[\da-f]+);?/gi, function (s, entity) {
```

2020-09-18 06:10 UTC, jridgewell commented on src/third_party/html-parser/html-parser.ts
>      let code = entity.charAt(0) === 'x' ? parseInt(entity.substr(1).toLowerCase(), 16) : parseInt(entity, 10);
This needs to be updated now. That's why I had split them in the initial https://github.com/ampproject/worker-dom/pull/947#discussion_r490598164

2020-09-18 18:28 UTC, samouri commented on src/third_party/html-parser/html-parser.ts
>      let code = entity.charAt(0) === 'x' ? parseInt(entity.substr(1).toLowerCase(), 16) : parseInt(entity, 10);
you mean to accept a capital `X` right? Fixed.

2020-09-18 19:26 UTC, jridgewell approved these changes

2020-09-18 19:26 UTC, jridgewell commented on src/third_party/html-parser/html-parser.ts
> +import { CharacterData } from '../../worker-thread/dom/CharacterData';
Unintentional import?

2020-09-18 19:56 UTC, samouri commented on src/third_party/html-parser/html-parser.ts
> +import { CharacterData } from '../../worker-thread/dom/CharacterData';
yeah, need to turn off auto-importing in vs code. will remove now?

2020-09-18 19:57 UTC, samouri commented on src/third_party/html-parser/html-parser.ts
> +import { CharacterData } from '../../worker-thread/dom/CharacterData';
hmm....already did actually

2020-09-18 20:22 UTC, kristoferbaxter approved these changes

2020-09-18 20:35 UTC, merged